// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project d805966b3c5b15ff "Case Study Hover Interaction - Community (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hover' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:case-study-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/xiSZ9YhaSYm4nT2nKnDM/GwFAnGgEmHtVHny6j0Ho/UzIxsLMN1.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["fXxQst9_z", "tgTqhvukb"];
var serializationHash = "framer-7AriV";
var variantClassNames = {
	fXxQst9_z: "framer-v-levpcp",
	tgTqhvukb: "framer-v-1ol9ygy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "fXxQst9_z",
	Hover: "tgTqhvukb",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fXxQst9_z",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fXxQst9_z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterbvqj7h = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("tgTqhvukb");
	});
	const onMouseLeavergol73 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("fXxQst9_z");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-levpcp",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"fXxQst9_z"}
						onMouseEnter={onMouseEnterbvqj7h}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								tgTqhvukb: {
									"data-framer-name": "Hover",
									onMouseLeave: onMouseLeavergol73,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-wsyu26"}
							data-framer-name={"3D Card"}
							layoutDependency={layoutDependency}
							layoutId={"mqcaDZRJI"}
							style={{
								transformPerspective: 1500,
							}}
						>
							<motion.div
								className={"framer-1xvuevi"}
								data-framer-name={"Front"}
								layoutDependency={layoutDependency}
								layoutId={"MmAS6CbEE"}
								style={{
									backgroundColor: "rgb(236, 242, 238)",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									originX: 0,
									rotateY: -1,
									z: 1,
								}}
								variants={{
									tgTqhvukb: {
										originY: 1,
										rotateY: -35,
									},
								}}
							>
								<motion.div
									className={"framer-12g2idc"}
									layoutDependency={layoutDependency}
									layoutId={"NRd1ChQsu"}
								>
									<SVG
										className={"framer-1k3v91a"}
										layoutDependency={layoutDependency}
										layoutId={"xdkKodXjF"}
										opacity={1}
										requiresOverflowVisible={false}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 11.957 12" overflow="visible"><g><path d="M 7.885 0.006 C 7.713 -0.019 7.538 0.033 7.407 0.15 C 7.275 0.267 7.2 0.437 7.2 0.615 L 7.2 4.265 C 7.2 4.605 7.469 4.88 7.8 4.88 L 11.358 4.88 C 11.532 4.88 11.697 4.802 11.811 4.668 C 11.925 4.533 11.976 4.354 11.951 4.177 C 11.647 2.016 9.992 0.319 7.885 0.006 Z" fill="rgb(155, 161, 165)"></path><path d="M 5.4 0.923 C 2.418 0.923 0 3.403 0 6.462 C 0 9.52 2.418 12 5.4 12 C 8.382 12 10.8 9.52 10.8 6.462 C 10.8 6.122 10.531 5.846 10.2 5.846 L 6 5.846 L 6 1.538 C 6 1.199 5.731 0.923 5.4 0.923 Z" fill="rgb(155, 161, 165)"></path></g></svg>'
										}
										withExternalLayout={true}
									>
										<SVG
											className={"framer-fzpi65"}
											layoutDependency={layoutDependency}
											layoutId={"u4Peg0LpZ"}
											opacity={1}
											requiresOverflowVisible={false}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.757 4.88" overflow="visible"><path d="M 0.685 0.006 C 0.513 -0.019 0.338 0.033 0.207 0.15 C 0.075 0.267 0 0.437 0 0.615 L 0 4.265 C 0 4.605 0.269 4.88 0.6 4.88 L 4.158 4.88 C 4.332 4.88 4.497 4.802 4.611 4.668 C 4.725 4.533 4.776 4.354 4.751 4.177 C 4.447 2.016 2.792 0.319 0.685 0.006 Z" fill="rgb(155, 161, 165)"></path></svg>'
											}
											withExternalLayout={true}
										/>
										<SVG
											className={"framer-1i1wo8p"}
											layoutDependency={layoutDependency}
											layoutId={"GhDi2gHNz"}
											opacity={1}
											requiresOverflowVisible={false}
											svg={
												'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 10.8 11.077" overflow="visible"><path d="M 5.4 0 C 2.418 0 0 2.48 0 5.538 C 0 8.597 2.418 11.077 5.4 11.077 C 8.382 11.077 10.8 8.597 10.8 5.538 C 10.8 5.199 10.531 4.923 10.2 4.923 L 6 4.923 L 6 0.615 C 6 0.276 5.731 0 5.4 0 Z" fill="rgb(155, 161, 165)"></path></svg>'
											}
											withExternalLayout={true}
										/>
									</SVG>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1ugjbc5"}
										fonts={["Inter-Bold"]}
										layoutDependency={layoutDependency}
										layoutId={"P5NvGhMO2"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-84002464-baa0-40a1-a1a1-82899aec539a, rgb(155, 161, 165))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItQm9sZA==",
													"--framer-font-size": "10px",
													"--framer-font-weight": "700",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-84002464-baa0-40a1-a1a1-82899aec539a, rgb(155, 161, 165)))",
												}}
											>
												{"CASE STUDY"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1lu0j7p"}
									layoutDependency={layoutDependency}
									layoutId={"y3Vczk6D3"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1pvwoij"}
										fonts={["Inter-SemiBold"]}
										layoutDependency={layoutDependency}
										layoutId={"JVZTh0yxU"}
										style={{
											"--extracted-14qxiz": "rgb(9, 130, 98)",
											"--extracted-1iakedh": "rgb(9, 130, 98)",
											"--extracted-2gxw0f": "rgb(9, 130, 98)",
											"--extracted-r6o4lv": "rgb(9, 130, 98)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-size": "24px",
													"--framer-font-weight": "600",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(9, 130, 98))",
												}}
											>
												{"How HelloFresh"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-size": "24px",
													"--framer-font-weight": "600",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-2gxw0f, rgb(9, 130, 98))",
												}}
											>
												{"Reduced CAC up"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-size": "24px",
													"--framer-font-weight": "600",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-1iakedh, rgb(9, 130, 98))",
												}}
											>
												{"to 20% with"}
											</motion.p>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-size": "24px",
													"--framer-font-weight": "600",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-14qxiz, rgb(9, 130, 98))",
												}}
											>
												{"Clarisights"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1ktoevt"}
									layoutDependency={layoutDependency}
									layoutId={"iJpfdUMSL"}
								>
									<motion.div
										className={"framer-wcvktl"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"iQoKJO4d2"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(156, 162, 166, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor: "rgb(10, 130, 98)",
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											opacity: 0.2,
										}}
									/>
									<motion.div
										className={"framer-lmrrgu"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"PufOCXoFL"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(156, 162, 166, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor: "rgb(10, 130, 98)",
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											opacity: 0.2,
										}}
									/>
									<motion.div
										className={"framer-1rlazd1"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"CtnA48pIW"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(156, 162, 166, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor: "rgb(10, 130, 98)",
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											opacity: 0.2,
										}}
									/>
									<motion.div
										className={"framer-ndfsf9"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"usBbjWSXq"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(156, 162, 166, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor: "rgb(10, 130, 98)",
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											opacity: 0.2,
										}}
									/>
								</motion.div>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 432,
										intrinsicWidth: 768,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												0 +
												(((componentViewport?.height || 376) - 0 - 0 - 376) /
													2 +
													0 +
													0) +
												30 +
												273.2,
										),
										pixelHeight: 864,
										pixelWidth: 1536,
										sizes: "73px",
										src: "https://framerusercontent.com/images/pOctq5tTR7nEvlKP1lml1URt8c.png?scale-down-to=1024&width=1536&height=864",
										srcSet:
											"https://framerusercontent.com/images/pOctq5tTR7nEvlKP1lml1URt8c.png?scale-down-to=512&width=1536&height=864 512w,https://framerusercontent.com/images/pOctq5tTR7nEvlKP1lml1URt8c.png?scale-down-to=1024&width=1536&height=864 1024w,https://framerusercontent.com/images/pOctq5tTR7nEvlKP1lml1URt8c.png?width=1536&height=864 1536w",
									}}
									className={"framer-ktj5an"}
									data-framer-name={"HelloFresh Logo 1536x864"}
									draggable={"false"}
									layoutDependency={layoutDependency}
									layoutId={"ELamZNTjb"}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 4e3,
										intrinsicWidth: 3611,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												0 +
												(((componentViewport?.height || 376) - 0 - 0 - 376) /
													2 +
													0 +
													0) +
												125.5,
										),
										pixelHeight: 8e3,
										pixelWidth: 7222,
										sizes: "38px",
										src: "https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=4096&width=7222&height=8000",
										srcSet:
											"https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=1024&width=7222&height=8000 924w,https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=2048&width=7222&height=8000 1848w,https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=4096&width=7222&height=8000 3697w,https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?width=7222&height=8000 7222w",
									}}
									className={"framer-1knqofx"}
									data-framer-name={"Leaf PNG Clipart"}
									draggable={"false"}
									layoutDependency={layoutDependency}
									layoutId={"ityXuMWhQ"}
								/>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 4e3,
										intrinsicWidth: 3611,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												0 +
												(((componentViewport?.height || 376) - 0 - 0 - 376) /
													2 +
													0 +
													0) +
												73.043,
										),
										pixelHeight: 8e3,
										pixelWidth: 7222,
										sizes: "38px",
										src: "https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=4096&width=7222&height=8000",
										srcSet:
											"https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=1024&width=7222&height=8000 924w,https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=2048&width=7222&height=8000 1848w,https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?scale-down-to=4096&width=7222&height=8000 3697w,https://framerusercontent.com/images/u59GRdumaTZtf5NWikdgzaRg1ho.png?width=7222&height=8000 7222w",
									}}
									className={"framer-1mnncvo"}
									data-framer-name={"Leaf PNG Clipart"}
									draggable={"false"}
									layoutDependency={layoutDependency}
									layoutId={"Ht4AIs9t_"}
									style={{
										rotateY: 180,
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-1s9afvl"}
								data-framer-name={"Card"}
								layoutDependency={layoutDependency}
								layoutId={"KP7ArFUD7"}
								style={{
									backgroundColor: "rgb(35, 109, 49)",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									originX: 0,
									originY: 1,
									rotate: 0,
								}}
								variants={{
									tgTqhvukb: {
										rotate: 4,
									},
								}}
							>
								<motion.div
									className={"framer-1gjm9vb"}
									layoutDependency={layoutDependency}
									layoutId={"PHXOxMOX_"}
									style={{
										rotate: -90,
									}}
									transformTemplate={transformTemplate1}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ukgrm4"}
										fonts={["Inter-SemiBold"]}
										layoutDependency={layoutDependency}
										layoutId={"c4gxxbyAt"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-size": "12px",
													"--framer-font-weight": "600",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)))",
												}}
											>
												{"CLICK TO READ"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<motion.div
								className={"framer-177n7sb"}
								data-framer-name={"Back"}
								layoutDependency={layoutDependency}
								layoutId={"V9kqdd6SU"}
								style={{
									backgroundColor: "rgb(211, 218, 205)",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									originX: 0,
									originY: 1,
									z: -1,
								}}
							>
								<motion.div
									className={"framer-1siwolw"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"IkE3CWTiV"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1favb9i"}
										fonts={["Inter-SemiBold"]}
										layoutDependency={layoutDependency}
										layoutId={"FBFtQzGMA"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-84002464-baa0-40a1-a1a1-82899aec539a, rgb(155, 161, 165))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
													"--framer-font-size": "12px",
													"--framer-font-weight": "600",
													"--framer-letter-spacing": "-0.04em",
													"--framer-text-alignment": "justify",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-84002464-baa0-40a1-a1a1-82899aec539a, rgb(155, 161, 165)))",
												}}
											>
												{
													"How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights. How Delivery Hero streamlines marketing reporting across all their brands with Clarisights"
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7AriV.framer-mdiye9, .framer-7AriV .framer-mdiye9 { display: block; }",
	".framer-7AriV.framer-levpcp { height: 376px; overflow: visible; position: relative; width: 292px; }",
	".framer-7AriV .framer-wsyu26 { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; justify-content: center; left: 0px; overflow: visible; padding: 0px; position: absolute; right: 0px; top: 0px; transform-style: preserve-3d; }",
	".framer-7AriV .framer-1xvuevi { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: 376px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 30px; position: relative; transform-style: preserve-3d; width: 292px; will-change: var(--framer-will-change-override, transform); z-index: 3; }",
	".framer-7AriV .framer-12g2idc { -webkit-user-select: none; align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; user-select: none; width: min-content; }",
	".framer-7AriV .framer-1k3v91a { height: 12px; position: relative; width: 12px; }",
	".framer-7AriV .framer-fzpi65 { height: 5px; left: 7px; position: absolute; top: 0px; width: 5px; }",
	".framer-7AriV .framer-1i1wo8p { height: 11px; left: 0px; position: absolute; top: 1px; width: 11px; }",
	".framer-7AriV .framer-1ugjbc5 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-7AriV .framer-1lu0j7p { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: min-content; }",
	".framer-7AriV .framer-1pvwoij, .framer-7AriV .framer-ukgrm4 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-7AriV .framer-1ktoevt { -webkit-user-select: none; align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; user-select: none; width: 100%; }",
	".framer-7AriV .framer-wcvktl { flex: none; height: 39px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 50px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7AriV .framer-lmrrgu { flex: none; height: 50px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 50px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7AriV .framer-1rlazd1 { flex: none; height: 68px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 50px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7AriV .framer-ndfsf9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 110px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 50px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7AriV .framer-ktj5an { -webkit-user-select: none; aspect-ratio: 1.7777777777777777 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 42px); overflow: visible; position: relative; user-select: none; width: 73px; }",
	".framer-7AriV .framer-1knqofx { -webkit-user-select: none; aspect-ratio: 0.90275 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 42px); overflow: visible; position: absolute; right: 77px; top: 126px; user-select: none; width: 38px; z-index: 1; }",
	".framer-7AriV .framer-1mnncvo { -webkit-user-select: none; aspect-ratio: 0.90275 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 42px); left: -14px; overflow: visible; position: absolute; top: 73px; user-select: none; width: 38px; z-index: 1; }",
	".framer-7AriV .framer-1s9afvl { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 318px; justify-content: center; left: calc(50.00000000000002% - 265px / 2); overflow: visible; padding: 0px; position: absolute; top: calc(50.00000000000002% - 318px / 2); transform-style: preserve-3d; width: 265px; z-index: 2; }",
	".framer-7AriV .framer-1gjm9vb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: absolute; right: -21px; top: 21%; width: min-content; z-index: 1; }",
	".framer-7AriV .framer-177n7sb { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: 376px; justify-content: center; left: 0px; overflow: visible; padding: 20px; position: absolute; top: calc(50.00000000000002% - 376px / 2); transform-style: preserve-3d; width: 292px; z-index: 1; }",
	".framer-7AriV .framer-1siwolw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-7AriV .framer-1favb9i { -webkit-user-select: none; flex: 1 0 0px; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-7AriV.framer-v-1ol9ygy .framer-1s9afvl { bottom: 15px; left: 40px; top: unset; }",
	'.framer-7AriV[data-border="true"]::after, .framer-7AriV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerUzIxsLMN1 = withCSS(Component, css, "framer-7AriV");
var stdin_default = FramerUzIxsLMN1;
FramerUzIxsLMN1.displayName = "Case Study 2";
FramerUzIxsLMN1.defaultProps = {
	height: 376,
	width: 292,
};
addPropertyControls(FramerUzIxsLMN1, {
	variant: {
		options: ["fXxQst9_z", "tgTqhvukb"],
		optionTitles: ["Default", "Hover"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerUzIxsLMN1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:case-study-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "fXxQst9_z",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d805966b3c5b15ffce428c34c21604a729736af270e1ce9a6d48ce1db0444249"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaseStudy2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"d805966b3c5b15ffce428c34c21604a729736af270e1ce9a6d48ce1db0444249"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var case_study_2_default = ComponentWithRoot;
export { case_study_2_default as default };
